### ISSUE TITLE
interlaced GIF

### ISSUE THREAD

**Issue by jonsneyers** [lecram/gifdec#1]
Hi!
Thanks for making this, I was looking for a small and simple GIF decoder and this one seems to work fine...

... except I don't think it handles interlaced GIFs correctly. Here's an example (the first frame is interlaced) :

![animhorse](https://user-images.githubusercontent.com/15010068/48422882-d5391f00-e75f-11e8-9f8f-23bc09c26de4.gif)

**Comment by Eagl61** [comment]
It does not work for me. I constantly get "Access violation" exception into "read_image_data" function, when using the "gd_get_frame" function.
PS. I use Windows, and use "<io.h>" instead of "<unistd.h>" .

**Comment by lecram** [comment]
Hi, @jonsneyers!
Thanks for reporting this bug.
It's fixed with commit ea1ed06c03dda22a042f1bdc187fedd6cd608e1d.
