### ISSUE TITLE
In Windows Environment Crash

### ISSUE THREAD

**Issue by runner111** [lecram/gifdec#3]
I porting the code to QT  environment and MinGW32 GCC environment, both of them same crash, and found the code will crash at read_image_data(gd_GIF *gif, int interlace), some like entries.prefix is error. It will be crash at line 370 
entry = table->entries[entry.prefix];

My environment Windows7 SDL2-2.0.9

**Comment by lecram** [comment]
Hi @runner111. Sorry for the long delay.

I can't reproduce the problem, but [I fixed a bug](https://github.com/lecram/gifdec/commit/54ab6c89c6bbb282971c0b5bfd13349048d84af9) related to Windows today.

If you're still having this issue after updating gifdec, please provide more info about the GIF you're using. Does it happen with any GIF? If no, can you attach an example GIF that triggers the problem?
