### ISSUE TITLE
Problem with a particular gif

### ISSUE THREAD

**Issue by arielm** [lecram/gifdec#8]
Hi,

Thanks for sharing this great piece of work!

[This gif](https://i.gifer.com/S5qc.gif) is not displayed correctly: the palette is incorrect and also the image is distorted.

Can you have a look at it?
10x

**Comment by lecram** [comment]
Hi @arielm.

I can't reproduce the problem.

Can you use [this code](https://gist.github.com/lecram/450f024d0ca9a77d7e09b576f65f5d89) to generate frame images and attach one incorrect frame to this issue?

You can convert PPM files to PNG using ImageMagick:

    $ convert gd_005.ppm gd_005.png

**Comment by arielm** [comment]
Hi Marcel,

Thanks for explode.c. I tested it with the gif in question and everything is ok.

I must be doing something wrong on my side then...
