### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by MiLeG** [lecram/gifdec#9]
Greetings,

I would like to use your code in my project, but as this [page ](https://choosealicense.com/no-permission/#for-users )suggests it's better to ask the owner to add a license instead of using unlicensed code.

Could you please then add a license? (preferably MIT 😄 )

**Comment by lecram** [comment]
Hi @MiLeG.

This library doesn't have a license because it is in the public domain. The last paragraph in the README should be [enough](http://cr.yp.to/publicdomain.html) to protect your right to use the code in any project.
